# This workflow will build a Golang project, create a release, and build artifacts for multiple OS platforms

name: Go

on:
  push:
    tags:
      - '*'  # Trigger for any tag
  pull_request:
    branches:
      - 'main'

permissions:
  contents: write  # Grant write permissions to the contents

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build for Linux
      run: go build -o tradingview-to-ibkr-linux64
      env:
        GOOS: linux
        GOARCH: amd64

    - name: Archive Linux build artifact
      uses: actions/upload-artifact@v3
      with:
        name: tradingview-to-ibkr-linux64
        path: tradingview-to-ibkr-linux64

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build for Windows
      run: go build -o tradingview-to-ibkr-win64.exe
      env:
        GOOS: windows
        GOARCH: amd64

    - name: Archive Windows build artifact
      uses: actions/upload-artifact@v3
      with:
        name: tradingview-to-ibkr-win64
        path: tradingview-to-ibkr-win64.exe

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build for macOS
      run: go build -o tradingview-to-ibkr-macos-arm64
      env:
        GOOS: darwin
        GOARCH: arm64

    - name: Archive macOS build artifact
      uses: actions/upload-artifact@v3
      with:
        name: tradingview-to-ibkr-macos-arm64
        path: tradingview-to-ibkr-macos-arm64

  create_release:
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows, build_macos]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4

    - name: Download Linux build artifact
      uses: actions/download-artifact@v3
      with:
        name: tradingview-to-ibkr-linux64
        path: ./build/linux64

    - name: Download Windows build artifact
      uses: actions/download-artifact@v3
      with:
        name: tradingview-to-ibkr-win64
        path: ./build/win64

    - name: Download macOS build artifact
      uses: actions/download-artifact@v3
      with:
        name: tradingview-to-ibkr-macos-arm64
        path: ./build/mac64

    - name: Extract tag name
      id: extract_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        body: |
          Changes in this release:
          - List your changes here
        draft: false
        prerelease: false

    - name: Upload Release Asset (Linux)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/linux64/tradingview-to-ibkr-linux64
        asset_name: tradingview-to-ibkr-linux64
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/win64/tradingview-to-ibkr-win64.exe
        asset_name: tradingview-to-ibkr-win64
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (macOS)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/mac64/tradingview-to-ibkr-macos-arm64
        asset_name: tradingview-to-ibkr-macos-arm64
        asset_content_type: application/octet-stream
